<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Set\ValueObject\LevelSetList;


/**
 * ->exclude(array(
 * // directories containing files with content that is autogenerated by `var_export`, which breaks CS in output code
 * 'Symfony/Component/DependencyInjection/Tests/Fixtures',
 * 'Symfony/Component/Routing/Tests/Fixtures/dumper',
 * // fixture templates
 * 'Symfony/Component/Templating/Tests/Fixtures/templates',
 * 'Symfony/Bundle/FrameworkBundle/Tests/Templating/Helper/Resources/Custom',
 * // generated fixtures
 * 'Symfony/Component/VarDumper/Tests/Fixtures',
 * // resource templates
 * 'Symfony/Bundle/FrameworkBundle/Resources/views/Form',
 * // explicit trigger_error tests
 * 'Symfony/Bridge/PhpUnit/Tests/DeprecationErrorHandler/',
 * ))
 */

return RectorConfig::configure()
    ->withPaths([
        dirname(__DIR__) . '/src',
    ])
    ->withSkip([
        dirname(__DIR__) . '/src/Symfony/Component/DependencyInjection/Tests/Fixtures',
        dirname(__DIR__) . '/src/Symfony/Component/Routing/Tests/Fixtures/dumper',
        dirname(__DIR__) . '/src/Symfony/Component/Templating/Tests/Fixtures/templates',
        dirname(__DIR__) . '/src/Symfony/Bundle/FrameworkBundle/Tests/Templating/Helper/Resources/Custom',
        dirname(__DIR__) . '/src/Symfony/Component/VarDumper/Tests/Fixtures',
        dirname(__DIR__) . '/src/Symfony/Bundle/FrameworkBundle/Resources/views/Form',
        dirname(__DIR__) . '/src/Symfony/Bridge/PhpUnit/Tests/DeprecationErrorHandler',
    ])
    // uncomment to reach your current PHP version
    ->withRules([
//        \Rector\Php81\Rector\Property\ReadOnlyPropertyRector::class
    \Rector\TypeDeclaration\Rector\ClassMethod\ReturnNeverTypeRector::class
    ])
    ->withSets([LevelSetList::UP_TO_PHP_81])
    ->withSkip([
//        \Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector::class,
//        \Rector\Php81\Rector\FuncCall\NullToStrictStringFuncCallArgRector::class
    ])
//    ->withPreparedSets(deadCode: false, codeQuality: false, naming: false, privatization: false)
    ;
